config {
    "type": "view",
    "name": "product_dim",
    "tags": ["sales_funnel_report"],
    "description": "Product level attributes with inventory and distribuition enrichment"
}

SELECT 
    p.id AS product_id,
    p.name AS product_name,
    p.category AS product_category,
    p.brand AS product_brand,
    p.department AS product_department,
    p.retail_price,
    p.cost,
    p.distribution_center_id,
    d.name AS distribution_center_name,
    d.latitude,
    d.longitude
FROM ${ref{"products"}} as p
LEFT JOIN ${ref{"distribution_centers"}} as d
ON p.distribution_center_id = d.id