config {
    "type": "view",
    "name": "order_details",
    "tags": ["sales_funnel_report"],
    "description": "Joined order_items with orders and calculated sales KPI per order line"
}

WITH base_items AS (
    SELECT
        id,
        order_id,
        user_id,
        product_id,
        sale_price,
        status,
        created_at,
        shipped_at,
        delivered_at,
        returned_at
    FROM ${ref{"order_items"}}
    WHERE created_at >= '2024-06-01'
),

orders_clean AS (
    SELECT
        order_id,
        user_id,
        status AS order_status,
        created_at AS order_created_at,
        delivered_at,
        returned_at,
        num_of_item
    FROM ${ref{"orders"}}
)
SELECT 
    os.user_id,
    os.order_id,
    bi.product_id,
    bi.sale_price,
    bi.status as item_status,
    os.order_status,
    bi.created_at as item_created_at,
    os.delivered_at,
    os.returned_at
FROM orders_clean AS os 
LEFT JOIN base_items as bi 
ON os.order_id = bi.order_id