config {
    type: "table",
    name: "sales_funnel_summary",
    tags: ["sales_funnel_report"],
    description: "Final report for funnel analysis"
    bigquery: {
        partitionBy: "event_date",
        clusterBy: ["user_id", "product_id"]
    }
}

SELECT 
    a.user_id,
    u.event_date,
    u.session_id,
    u.browser,
    u.traffic_source,
    s.age_band,
    s.gender,
    p.product_id,
    p.product_name,
    p.product_category
    p.product_brand,
    p.product_department,
    p.retail_price,
    o.sale_price,
    o.item_status,
    o.order_status,
    CASE
        WHEN b.event_type = 'add_to_cart' THEN 1
        ELSE 0
    END AS added_to_cart,
    CASE
        WHEN b.event_type = 'purchase' THEN 1
        ELSE 0
    END AS purchase,
    CASE
        WHEN o.returned_at IS NOT NULL THEN 'True'
        ELSE 'False'
    END AS is_returned
FROM ${ref{"order_details"}} AS o
LEFT JOIN ${ref{"product_dim"}} AS p
ON o.product_id = p.product_id
LEFT JOIN ${ref{"user_behavior"}} AS u
ON o.user_id = u.user_id
LEFT JOIN ${ref{"user_segments"}} as s
ON o.user_id = s.user_id